spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:matzzang}
spring.datasource.username=${DB_USERNAME:matzzang}
spring.datasource.password=${DB_PASSWORD:matzzang}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.com.sprint.mission.matzzang=DEBUG
