spring.application.name=matzzang
spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# flyway ??

# ????? true?? ???? ?? ?? true
spring.flyway.enabled=true      

# DB ?? ??? flyway? ??? ?? true, ??? false
spring.flyway.baseline-on-migrate=false

# DB SCHEMA? ?? ??? ??(src/main/resources/schema)
spring.flyway.locations=classpath:schema

# migrate ? ??? ??
spring.flyway.validate-on-migrate=true

# JWT Access/Refresh Token 만료 시간 (ms)
jwt.access-token-expiration-ms=1800000
jwt.refresh-token-expiration-ms=1209600000

