spring.application.name=matzzang
spring.profiles.active=local

# hibernate? entity ??? ?? ???? ??? ??? none?? ?? (flyway ??)
spring.jpa.hibernate.ddl-auto=none
# ? ???? ??? ?? ??? ??? ??? false? ??
spring.jpa.open-in-view=false

# flyway ??

# ????? true?? ???? ?? ?? true
spring.flyway.enabled=true      

# DB ?? ??? flyway? ??? ?? true, ??? false
spring.flyway.baseline-on-migrate=false

# DB SCHEMA? ?? ??? ??(src/main/resources/schema)
spring.flyway.locations=classpath:schema

# migrate ? ??? ??
spring.flyway.validate-on-migrate=true

